version: 2

project_name: openilink-hub

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    binary: openilink-hub
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CGO_CFLAGS=-Wno-stringop-overread -Wno-constant-conversion
    ldflags: &ldflags
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

  - id: windows-amd64
    binary: openilink-hub
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    ldflags: *ldflags

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  extra_files:
    - glob: darwin-archives/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: openilink
    name: openilink-hub
  extra_files:
    - glob: darwin-archives/*

dockers:
  - image_templates:
      - "ghcr.io/openilink/openilink-hub:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
    ids: [linux-amd64]
docker_manifests:
  - name_template: "ghcr.io/openilink/openilink-hub:{{ .Version }}"
    image_templates:
      - "ghcr.io/openilink/openilink-hub:{{ .Version }}-amd64"
  - name_template: "ghcr.io/openilink/openilink-hub:latest"
    image_templates:
      - "ghcr.io/openilink/openilink-hub:{{ .Version }}-amd64"
